<?php

/**
 * sfGuardUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OfficeMerits
 * @subpackage model
 * @author     Joshua Estes
 * @version    SVN: $Id$
 */
class sfGuardUserPermission extends PluginsfGuardUserPermission
{
}
