Badge:
  actAs:
    Timestampable: ~
    Blameable: ~
    Sluggable: ~
  column:
    icon:
      type: text
      length: 255
    title:
      type: text
      length: 255
      notnull: true
    description:
      type: clob
